openapi: "3.0.3"
info:
  title: ColourYou API
  description: "L'API du moment"
  version: 2.0.0
  servers:
  - url: https://colouryou.onrender.com/
    description: Lien de l'API en ligne
tags:
  - name: user
    description: Everything about the users
  - name: photo
    description: Access to the photos
  - name: couleur
    description: See the couleurs
paths:
  /users:
    get:
      tags: 
        - user
      summary: Retourne une liste d'utilisateurs
      description: Optional extended description in CommonMark or HTML
      parameters:
        - name: username
          in: query
          description: Le pseudo de l'utilisateur qui doit être retourné
          required: true
          schema:
            type: string
        - name: name
          in: query
          description: Le nom de l'utilisateur qui doit être retourné
          required: true
          schema:
            type: string
        - name: surname
          in: query
          description: Le prénom de l'utilisateur qui doit être retourné
          required: true
          schema:
            type: string
      responses:
        '200':
          description: La liste des utilisateurs
          content:
            application/json:
              schema:
              #  $ref: '#/components/models/user'
                type: array
                items: 
                  type: string
    post:
      tags: 
        - user
      summary: Créer un utilisateur
      description: Insérer les champs nécessaires pour la création d'un utilisateur
      responses:
        '200':
          description: Utilisateur 
        requestBody:  
          content:
            application/json:
              schema: 
                type: object
                properties:
                  name:
                    type: string
                    description: Prénom de l'utilisateur
                    example: John
                  surname:
                    type: string
                    description: Nom de l'utilisateur
                    example: Doe
                  email:
                    type: string
                    description: Mail de l'utilisateur
                    example: johndoe@hotmail.com
                  password:
                    type: string
                    description: Mot de passe de l'utilisateur
                    example: test1234
                  username:
                    type: string
                    description: Pseudo de l'utilisateur
                    example: john.doe
                  age:
                    type: number
                    description: L'âge de l'utilisateur
                    example: 24
                required:
                  - name
                  - surname
                  - email
                  - password
                  - username
        '400':
          description: Champs incorrect(s)
        '404':
          description: 'Page non trouvée'
  /users/{id}:
    get:
      tags: 
        - user
      summary: Trouver les informations d'un utilisateur par son id
      parameters:
        - name: id
          in: query
          description: L'identifiant unique de l'utilisateur
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                _id: 
                  type: string
                  description: ID unique de l'utilisateur
                  example: "636cb9790788f89587f12895"
                name:
                  type: string
                  description: Prénom de l'utilisateur
                  example: John
                surname:
                  type: string
                  description: Nom de l'utilisateur
                  example: Doe
      responses:
        '200':
          description: Utilisateur crée
        '405':
          description: Méthode non autorisée      
  /users/login:
    get:
      tags: 
        - user
      summary: Connecte l'utilisateur à l'API
      description: Se connecter à l'API
      parameters:
        - name: username
          in: path
          description: Le nom d'utilisateur
          required: true
          schema:
            type: string
        - name: password
          in: path
          description: Mot de passe
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Pseudo de l'utilisateur
                  example: john.doe
                password:
                  type: string
                  description: Mot de passe de l'utilisateur
                  example: john1234
      responses:
        '200':
          description: Utilisateur connecté 
        '400':
          description: Le nom d'utilisateur et/ou le mot de passe incorrect
        '404':
          description: Ressource non trouvée
  /users/logout:
    get:
      tags: 
        - user
      summary: Déconnecte l'utilisateur
      description: Déconnexion de l'utilisateur de l'API
      responses:
        '200':
          description: L'utilisateur est déconnecté avec succès
        '404': 
          description: Page non trouvée
  /photos:
    get:
      tags:
        - photo
      summary: Retourne une liste des photos
      description: ''
    post:
      tags:
        - photo
      summary: Ajouter une photo
      description: ''
      operationId: uploadFile
      parameters:
        - name: location
          in: query
          description: Les coordonnées géographiques de la photo 
          required: true
          schema:
            type: string
        - name: userId
          in: query
          description: L'identifiant de l'utilisateur qui a posté la photo
          required: true
          schema:
            type: string
        - name: couleurId
          in: query
          description: L'identifiant de la couleur en lien avec la photo
          required: true
          schema:
            type: string
        - name: date
          in: query
          description: La date de la photo
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
                  description: ID de la photo
                  example: 63721b553ede76ff89a1fgtz
                description:
                  type: string
                  example: '#1F1F1F'
                datePosted:
                  type: date
                  example: 07.11.2022
                location:
                  type: string
                  example: Yverdon-les-Bains
                url:
                  type: string
                  example: https://colouryou.onrender.com/photos/63721b553ede76ff89a1fgtz
                user:
                  type: string
                  example: Par john.doe
                color: 
                  type: string
                  example: Bleu marine
                
      responses:
        '200':
          description: Photo ajoutée avec succès
        '400':
          description: ''
        '404':
          description: Page non trouvée
  
  /photos/{id}:
    get:
      tags:
        - photo
      summary: Affiche la photo par son ID
      description: ''
      parameters:
        - name: photoId
          in: path
          description: ID de la photo sélectionnée
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
                  format: binary
                  description: ID de la photo
                  example: 63721b553ede76ff89a1fgtz
    put:
      tags:
        - photo
      summary: Met à jour la photo par son ID
      description: ''
      parameters:
        - name: photoId
          in: path
          description: ID de la photo sélectionnée
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                photoId:
                  type: string
                  description: ID de la photo
                  example: 63721b553ede76ff89a1fgtz
    delete:
      tags:
        - photo
      summary: Supprime la photo par son ID
      description: ''
      parameters:
        - name: photoId
          in: path
          description: ID de la photo sélectionnée
          required: false
          schema:
            type: string
  /couleurs:
    get:
      tags:
        - couleur
      summary: Retourne une liste des couleurs
      description: ''
      parameters:
        - name: name
          in: query
          description: Le nom de la couleur
          schema:
            type: string
        - name: hex
          in: query
          description: Le code hexadécimal de la couleur
          schema:
            type: string
        - name: datePosted
          in: query
          description: La date de la couleur
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nom de la couleur
                  example: Bleu marine
                hex:
                  type: string
                  description: Code hexadécimal de la couleur
                  example: '#1F1F1F'
                datePosted:
                  type: date
                  description: 14.11.2022
              examples:
                name: Vert pomme
                hex: '#222222'
                datePosted: 14.12.2022
      responses:
        '200':
          description: OK
        '400':
          description: ''
        '404':
          description: Page non trouvée
        '405':
          description: Méthode non autorisée
    put:
      tags:
        - couleur
      summary: Met à jour les couleurs
      description: ''
  /couleurs/{id}:
    get:
      tags:
        - couleur
      summary: Affiche la couleur par son ID
      description: ''
      parameters:
        - name: couleurId
          in: query
          description: ID de la couleur
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nom de la couleur
                  example: Bleu marine
                hex:
                  type: string
                  description: Code hexadécimal de la couleur
                  example: '#1F1F1F'
                datePosted:
                  type: date
                  description: 07/09/2022
    post:
      tags:
        - couleur
      summary: Modifier la couleur par son ID
      description: ''
      parameters:
        - name: couleurId
          in: path
          description: ID de la couleur
          required: true
          unique: true
          schema:
            type: string
        - name: name
          in: path
          description: Nom de la couleur
          required: true
          unique: true
          schema:
            type: string
        - name: hex
          in: path
          description: Code hexadécimal de la couleur
          required: true
          unique: true
          schema:
            type: string
        - name: datePosted
          in: path
          description: Date à laquelle la couleur apparaît
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nom de la couleur
                  example: Bleu marine
                hex:
                  type: string
                  description: Code hexadécimal de la couleur
                  example: '#1F1F1F'
                datePosted:
                  type: date
                  description: Date à laquelle la couleur apparaît
      responses:
        '200':
          description: Couleur ajoutée avec succès
        '400':
          description: ''
        '404':
          description: Page non trouvée
    delete:
      tags:
        - couleur
      summary: Supprimer la couleur par son ID
      description: ''
    
    
    